language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "E6vCBMCw031Xmc5kawuNm0tE5u7mLNloxDBqk2kEj19n7SAfK14vsGDFnU1FlRZkeauCu42v4IkvFd8vWpvy6bXsHG1byP/qpoIYw4KDLutIV3Pht2wdWgwVkIyf2XVLeH1vsy8Il1y86ki2cAyxT2ViERLsk0iIDl0F92eih6kzSaxcsiLdbQmmVmyAaxxMhqOHzNJ9GDJdoFZVjOsLL1MpBx3Tlyj72fnHnzy4yc/P3g9rj14Ma3ul/acWFKCP7UZw/D7RFDQkSSr6VX8QbypgTFByTas5YVbxnI7U5jgp++/owjHUm82KUnQn7qMKaZKxTmZOdNkWiDICiPz6WhRV3rov0QdJlhy0fTaP6SElGP8FDUFhHS2W+l1PfZD3o0kqQ3PjDHq+tLWUcP/8SlUCSpujX0PXVf1tT1FeMJXLo9xJptzRFLKiVMh4r9DZhWO1NiXbEE0tLIPQeOX+vzxMIQGCx6yxUoKNzRrpEFYtJ12AvHX0na0PFxkz8Pe5kS24sMoFhpdxu7rzeO+57KSuvBniN39QPOv7NczrslM2KWx6OeUSt6TVUA++G56BZPi0jtVjITADmqsIYAYFio89fp4sjiDcKOrmSlEFCjYwkSLjzKPuGzjiNFDfNO9jQQR4Zfkv8BAeyFSmZ1yY8k9JLt0ucL69eVVdxkKJs88="

addons:
  coverity_scan:
    project:
      name: "wkliao/parallel-netcdf"
      description: "Parallel netCDF build submitted via Travis CI"
    notification_email: wkliao@eecs.northwestern.edu
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

before_install:
  - test -n $CC && unset CC
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran
  - sudo apt-get install -y mpich2
  - autoreconf
  # string substritute for SVN keyword LastChangedDate
  # Below is for Redhat
  # - DateStr=`stat -f "%Sm" -t "%F %T %z (%a, %d %b %Y)" configure.in` ; sed -e "s/LastChangedDate/LastChangedDate: $DateStr /g" -i "" configure
  # Below is for Ubuntu
  - DateStr=`date -r configure.in +"%F %T %z (%a, %d %b %Y)"` ; sed -e "s/LastChangedDate/LastChangedDate $DateStr /g" -i configure

script:
  - ./configure
  - make clean
  - make
  - make tests
  - make check
  
after_failure:
  - cat ./config.log

notifications:
  email: false
